### ISSUE TITLE
Multiple BNO055

### ISSUE THREAD

**Issue by ghost** [TedMeyers/XYZ-robo#1]
Hey Ted!

Great library! Sorry this isn't really an issue but I wasn't sure how to contact you.
I wondering how I can modify your library to be able to communicate with two sensors at once on different addresses?

Can I modify the constructor to take an argument?

Appreciate any help.

Sam

**Comment by ghost** [comment]
Already works. My fault.

**Comment by TedMeyers** [comment]
Sammy,

Just wanted to verify that you have resolved both your issues?

Ted

**Comment by ghost** [comment]
Hey Ted!

Both of my issues were with my brain not your library. It is great.
Shouldn't post when tired.

I have modified XYZ_BNO055::setup to take accelerometer offsets as
arguments and apply them. Seems to work great for cold starts with my two
sensors.

I can send you the code if it interests you?

Cheers!

Sam
